(function(){
'use strict';
var user=null,autoStarted=false,currentMode='login';
function E(id){return document.getElementById(id)}
function text(id,v){var e=E(id);if(e)e.textContent=v||''}
function showGate(on){var g=E('authGate');if(g)g.classList.toggle('show',!!on)}
function showVerify(on,email){var v=E('verifyOverlay');if(v)v.classList.toggle('show',!!on);if(email)text('verifyEmail',email)}
function clearMsgs(){text('authMsg','');text('signupMsg','');text('verifyMsg','')}
function validEmail(v){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(v||'').trim())}
function setMode(mode){currentMode=mode==='signup'?'signup':'login';var l=E('authLoginMode'),s=E('authSignupMode');if(l)l.classList.toggle('active',currentMode==='login');if(s)s.classList.toggle('active',currentMode==='signup');clearMsgs()}
function profileFromAccount(u){if(!u||!u.signedIn)return;var k='attendance_profile_v81',p={},changed=false;try{p=JSON.parse(localStorage.getItem(k)||'{}')||{}}catch(e){}if((!p.name||p.name==='My Profile')&&u.name){p.name=u.name;changed=true}if(!p.photo&&u.photo){p.photo=u.photo;changed=true}if(changed){localStorage.setItem(k,JSON.stringify(p));var n=E('profileName');if(n)n.value=p.name||'';var a=E('profilePreview');if(a&&p.photo)a.src=p.photo;var ta=E('topAvatar');if(ta&&p.photo)ta.src=p.photo;var tn=E('topName');if(tn)tn.textContent=p.name||'My Profile'}}
function account(u){user=u||{};var signed=!!user.signedIn,verified=!!user.emailVerified,expected=signed?String(user.uid||''):'';if(typeof window.attendanceRuntimeUid==='string'&&window.attendanceRuntimeUid!==expected){location.reload();return}if(signed&&!verified){showGate(true);showVerify(true,user.email||'');return}showVerify(false);showGate(!signed);if(!signed){if(user.setupError)text('authMsg',user.setupError);return}var av=E('cloudAvatar');if(av)av.src=user.photo||'profile-placeholder.svg';text('cloudName',user.name||'My Account');text('cloudEmail',user.email||'');clearMsgs();profileFromAccount(user);startAuto()}
function snap(){var storage=window.attendanceSnapshotCurrentUser?window.attendanceSnapshotCurrentUser():{},o={version:3,policyVersion:126,userUid:String(window.attendanceRuntimeUid||''),savedAt:new Date().toISOString(),storage:storage};return JSON.stringify(o)}
function oldRecoveryKey(){return String(window.attendanceUserPrefix||'attendance_guest__')+'backup_recovery_password_v126'}
function oldRecoveryPassword(){try{if(window.Android&&Android.secureGet)return String(Android.secureGet(oldRecoveryKey())||'')}catch(e){}return''}
function unb64u(v){var s=atob(String(v||'')),a=new Uint8Array(s.length),i;for(i=0;i<s.length;i++)a[i]=s.charCodeAt(i);return a}
function legacyKeyMaterial(){var uid=String((user&&user.uid)||window.attendanceRuntimeUid||''),email=String((user&&user.email)||'').trim().toLowerCase();return'MyAttendance|cloud-backup|aes256gcm|v1|'+uid+'|'+email+'|mab-2026-10-client-envelope'}
function legacyKey(){if(!window.crypto||!crypto.subtle)return Promise.reject(new Error('Secure backup decryption is unavailable'));return crypto.subtle.digest('SHA-256',new TextEncoder().encode(legacyKeyMaterial())).then(function(h){return crypto.subtle.importKey('raw',h,{name:'AES-GCM'},false,['decrypt'])})}
function decryptLegacyV3(o){var current=String((user&&user.uid)||window.attendanceRuntimeUid||'');if(o.userUid&&current&&String(o.userUid)!==current)return Promise.reject(new Error('This backup belongs to a different account.'));return legacyKey().then(function(k){return crypto.subtle.decrypt({name:'AES-GCM',iv:unb64u(o.iv)},k,unb64u(o.ciphertext))}).then(function(buf){return new TextDecoder().decode(buf)}).catch(function(){throw new Error('This older encrypted backup could not be opened with this account.')})}
function decryptLegacy(payload){var o;try{o=JSON.parse(payload||'{}')}catch(e){return Promise.reject(new Error('Restore file is invalid'))}if(!o||!o.encrypted)return Promise.resolve(payload);if(o.version===4){var pw=oldRecoveryPassword();if(!pw)return Promise.reject(new Error('This older backup used a recovery password that is no longer available on this device.'));if(!window.AttendanceBackupCrypto)return Promise.reject(new Error('Legacy backup crypto is unavailable'));return AttendanceBackupCrypto.decrypt(o,pw,String((user&&user.uid)||window.attendanceRuntimeUid||''))}if(o.version===3&&o.cipher==='AES-256-GCM')return decryptLegacyV3(o);if(o.version===5)return Promise.reject(new Error('Device-protected backup could not be unlocked.'));return Promise.reject(new Error('Encrypted backup format is unsupported'))}
function applyRestore(plain){var o=JSON.parse(plain||'{}'),s=o.storage||{},current=String(window.attendanceRuntimeUid||'');if(o.userUid&&current&&String(o.userUid)!==current)throw new Error('This backup belongs to a different account.');if(window.AttendancePolicy&&AttendancePolicy.validateStorage){var check=AttendancePolicy.validateStorage(s);if(!check.ok)throw new Error(check.error||'Backup validation failed')}var ok=window.attendanceRestoreCurrentUser?window.attendanceRestoreCurrentUser(s):false;if(!ok)throw new Error('Restore failed safely. Your existing data was kept.');localStorage.setItem('attendance_cloud_last_v10',String(Date.now()));text('cloudStatus','Restore verified. Reloading…');setTimeout(function(){location.reload()},120)}
function backup(){if(!user||!user.signedIn||!user.emailVerified)return;if(!window.Android||!Android.secureCloudBackup){text('cloudStatus','Secure device backup is unavailable in this build.');return}text('cloudStatus','Waiting for device verification…');Android.secureCloudBackup(snap())}
function restore(){if(!user||!user.signedIn||!user.emailVerified)return;if(!window.Android||!Android.secureCloudRestore){text('cloudStatus','Secure restore is unavailable in this build.');return}var go=function(){text('cloudStatus','Waiting for device verification…');Android.secureCloudRestore()};if(window.appDialog){window.appDialog('Restore backup?','Android will ask for your fingerprint, face, PIN, pattern or device password. Your current data is replaced only after the backup is decrypted and validated.',[{label:'Continue',kind:'primary'},{label:'Cancel',kind:'outline'}],function(i){if(i===0)go()})}else if(confirm('Verify with your device security and restore the cloud backup?'))go()}
function startAuto(){if(autoStarted)return;autoStarted=true;text('cloudStatus','Ready. Backup and Restore are protected by your phone security.')}
function doLogin(){var em=String(E('loginEmail').value||'').trim(),pw=String(E('loginPassword').value||'');clearMsgs();if(!validEmail(em)){text('authMsg','Please enter a valid email address.');return}if(!pw){text('authMsg','Please enter your password.');return}text('authMsg','Signing in…');Android.emailSignIn(em,pw)}
function doSignup(){var em=String(E('signupEmail').value||'').trim(),pw=String(E('signupPassword').value||''),cp=String(E('signupConfirm').value||'');clearMsgs();if(!validEmail(em)){text('signupMsg','Please enter a valid email address.');return}if(pw.length<6){text('signupMsg','Password must be at least 6 characters.');return}if(pw!==cp){text('signupMsg','Passwords do not match.');return}if(!E('termsAgree').checked){text('signupMsg','Please accept the Terms & Privacy Policy.');return}text('signupMsg','Creating your account…');Android.emailSignUp(em,pw)}
function togglePassword(btn){var id=btn.getAttribute('data-password-target'),inp=E(id);if(!inp)return;inp.type=inp.type==='password'?'text':'password';btn.textContent=inp.type==='password'?'◉':'◎'}
window.onNativeAuthChanged=function(u){account(u||{})};
window.onNativeAuthError=function(m){if(E('verifyOverlay')&&E('verifyOverlay').classList.contains('show'))text('verifyMsg',m||'Authentication failed');else text(currentMode==='signup'?'signupMsg':'authMsg',m||'Authentication failed')};
window.onNativeAuthNotice=function(m){if(E('verifyOverlay')&&E('verifyOverlay').classList.contains('show'))text('verifyMsg',m||'');else text(currentMode==='signup'?'signupMsg':'authMsg',m||'')};
window.onCloudBackupResult=function(ok,msg,ts){text('cloudStatus',ok?'Backup saved securely':(msg||'Backup failed'));if(ok&&ts){localStorage.setItem('attendance_cloud_last_v10',String(ts));localStorage.setItem('attendance_cloud_last_manual_v122',String(ts))}};
window.onCloudRestore=function(payload){decryptLegacy(payload).then(function(plain){applyRestore(plain)}).catch(function(e){text('cloudStatus',(e&&e.message)||'Restore file is invalid')})};
window.onDeviceCloudRestore=function(plain){try{applyRestore(plain)}catch(e){text('cloudStatus',(e&&e.message)||'Restore file is invalid')}};
window.onCloudRestoreError=function(m){text('cloudStatus',m||'No cloud backup found')};
function init(){var gi=E('googleLoginBtn'),gs=E('googleSignupBtn'),el=E('emailLoginBtn'),es=E('emailSignupBtn'),fp=E('forgotPasswordBtn'),bk=E('cloudBackupBtn'),rs=E('cloudRestoreBtn'),so=E('cloudSignOutBtn'),cv=E('checkVerifiedBtn'),rv=E('resendVerificationBtn'),vs=E('verifySignOutBtn'),sw=document.querySelectorAll('[data-switch-auth]'),eyes=document.querySelectorAll('[data-password-target]'),i;if(gi)gi.onclick=function(){clearMsgs();text('authMsg','Opening Google…');Android.googleSignIn()};if(gs)gs.onclick=function(){clearMsgs();text('signupMsg','Opening Google…');Android.googleSignIn()};if(el)el.onclick=doLogin;if(es)es.onclick=doSignup;if(fp)fp.onclick=function(){var em=String(E('loginEmail').value||'').trim();clearMsgs();if(!validEmail(em)){text('authMsg','Enter your email first.');return}text('authMsg','Sending reset email…');Android.resetPassword(em)};if(bk)bk.onclick=backup;if(rs)rs.onclick=restore;if(so)so.onclick=function(){if(confirm('Sign out of this account?'))Android.googleSignOut()};if(cv)cv.onclick=function(){text('verifyMsg','Checking verification…');Android.checkEmailVerified()};if(rv)rv.onclick=function(){text('verifyMsg','Sending verification email…');Android.resendVerification()};if(vs)vs.onclick=function(){Android.googleSignOut();showVerify(false)};for(i=0;i<sw.length;i++)sw[i].onclick=function(){setMode(this.getAttribute('data-switch-auth'))};for(i=0;i<eyes.length;i++)eyes[i].onclick=function(){togglePassword(this)};var ab=E('authBackBtn');if(ab)ab.onclick=function(){if(currentMode==='signup')setMode('login')};setMode('login');if(window.Android&&Android.authState)Android.authState()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();