(function(){
'use strict';
var user=null,lastSig='',timer=null,autoStarted=false,currentMode='login';
function E(id){return document.getElementById(id)}
function text(id,v){var e=E(id);if(e)e.textContent=v||''}
function showGate(on){var g=E('authGate');if(g)g.classList.toggle('show',!!on)}
function showVerify(on,email){var v=E('verifyOverlay');if(v)v.classList.toggle('show',!!on);if(email)text('verifyEmail',email)}
function clearMsgs(){text('authMsg','');text('signupMsg','');text('verifyMsg','')}
function validEmail(v){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(v||'').trim())}
function setMode(mode){currentMode=mode==='signup'?'signup':'login';var l=E('authLoginMode'),s=E('authSignupMode');if(l)l.classList.toggle('active',currentMode==='login');if(s)s.classList.toggle('active',currentMode==='signup');clearMsgs()}
function profileFromAccount(u){if(!u||!u.signedIn)return;var k='attendance_profile_v81',p={},changed=false;try{p=JSON.parse(localStorage.getItem(k)||'{}')||{}}catch(e){}if((!p.name||p.name==='My Profile')&&u.name){p.name=u.name;changed=true}if(!p.photo&&u.photo){p.photo=u.photo;changed=true}if(changed){localStorage.setItem(k,JSON.stringify(p));var n=E('profileName');if(n)n.value=p.name||'';var a=E('profilePreview');if(a&&p.photo)a.src=p.photo;var ta=E('topAvatar');if(ta&&p.photo)ta.src=p.photo;var tn=E('topName');if(tn)tn.textContent=p.name||'My Profile'}}
function account(u){user=u||{};var signed=!!user.signedIn,verified=!!user.emailVerified;if(signed&&!verified){showGate(true);showVerify(true,user.email||'');return}showVerify(false);showGate(!signed);if(!signed){if(user.setupError)text('authMsg',user.setupError);return}var av=E('cloudAvatar');if(av)av.src=user.photo||'profile-placeholder.svg';text('cloudName',user.name||'My Account');text('cloudEmail',user.email||'');clearMsgs();profileFromAccount(user);startAuto()}
function snap(){var o={version:1,savedAt:new Date().toISOString(),storage:{}},i,k;for(i=0;i<localStorage.length;i++){k=localStorage.key(i);if(k&&k.indexOf('attendance_')===0&&k.indexOf('attendance_cloud_')!==0)o.storage[k]=localStorage.getItem(k)}return JSON.stringify(o)}
function sig(s){var h=0,i;for(i=0;i<s.length;i++)h=((h<<5)-h+s.charCodeAt(i))|0;return s.length+':'+h}
function backup(manual){if(!user||!user.signedIn||!user.emailVerified||!window.Android||!Android.cloudBackup)return;var s=snap(),x=sig(s);if(!manual&&x===lastSig)return;text('cloudStatus',manual?'Backing up…':'Syncing…');lastSig=x;Android.cloudBackup(s)}
function startAuto(){if(autoStarted)return;autoStarted=true;timer=setInterval(function(){backup(false)},45000);setTimeout(function(){backup(false)},5000)}
function restore(){if(!user||!user.signedIn||!user.emailVerified)return;if(confirm('Restore your latest cloud backup? Current local app data will be replaced.')){text('cloudStatus','Restoring…');Android.cloudRestore()}}
function doLogin(){var em=String(E('loginEmail').value||'').trim(),pw=String(E('loginPassword').value||'');clearMsgs();if(!validEmail(em)){text('authMsg','Please enter a valid email address.');return}if(!pw){text('authMsg','Please enter your password.');return}text('authMsg','Signing in…');Android.emailSignIn(em,pw)}
function doSignup(){var em=String(E('signupEmail').value||'').trim(),pw=String(E('signupPassword').value||''),cp=String(E('signupConfirm').value||'');clearMsgs();if(!validEmail(em)){text('signupMsg','Please enter a valid email address.');return}if(pw.length<6){text('signupMsg','Password must be at least 6 characters.');return}if(pw!==cp){text('signupMsg','Passwords do not match.');return}if(!E('termsAgree').checked){text('signupMsg','Please accept the Terms & Privacy Policy.');return}text('signupMsg','Creating your account…');Android.emailSignUp(em,pw)}
function togglePassword(btn){var id=btn.getAttribute('data-password-target'),inp=E(id);if(!inp)return;inp.type=inp.type==='password'?'text':'password';btn.textContent=inp.type==='password'?'◉':'◎'}
window.onNativeAuthChanged=function(u){account(u||{})};
window.onNativeAuthError=function(m){if(E('verifyOverlay')&&E('verifyOverlay').classList.contains('show'))text('verifyMsg',m||'Authentication failed');else text(currentMode==='signup'?'signupMsg':'authMsg',m||'Authentication failed')};
window.onNativeAuthNotice=function(m){if(E('verifyOverlay')&&E('verifyOverlay').classList.contains('show'))text('verifyMsg',m||'');else text(currentMode==='signup'?'signupMsg':'authMsg',m||'')};
window.onCloudBackupResult=function(ok,msg,ts){text('cloudStatus',ok?'Cloud backup saved':(msg||'Backup failed'));if(ok&&ts)localStorage.setItem('attendance_cloud_last_v10',String(ts))};
window.onCloudRestore=function(payload){try{var o=JSON.parse(payload||'{}'),s=o.storage||{},k;for(k in s)if(s.hasOwnProperty(k))localStorage.setItem(k,s[k]);localStorage.setItem('attendance_cloud_last_v10',String(Date.now()));location.reload()}catch(e){text('cloudStatus','Restore file is invalid')}};
window.onCloudRestoreError=function(m){text('cloudStatus',m||'No cloud backup found')};
function init(){var gi=E('googleLoginBtn'),gs=E('googleSignupBtn'),el=E('emailLoginBtn'),es=E('emailSignupBtn'),fp=E('forgotPasswordBtn'),bk=E('cloudBackupBtn'),rs=E('cloudRestoreBtn'),so=E('cloudSignOutBtn'),cv=E('checkVerifiedBtn'),rv=E('resendVerificationBtn'),vs=E('verifySignOutBtn'),sw=document.querySelectorAll('[data-switch-auth]'),eyes=document.querySelectorAll('[data-password-target]'),i;if(gi)gi.onclick=function(){clearMsgs();text('authMsg','Opening Google…');Android.googleSignIn()};if(gs)gs.onclick=function(){clearMsgs();text('signupMsg','Opening Google…');Android.googleSignIn()};if(el)el.onclick=doLogin;if(es)es.onclick=doSignup;if(fp)fp.onclick=function(){var em=String(E('loginEmail').value||'').trim();clearMsgs();if(!validEmail(em)){text('authMsg','Enter your email first.');return}text('authMsg','Sending reset email…');Android.resetPassword(em)};if(bk)bk.onclick=function(){backup(true)};if(rs)rs.onclick=restore;if(so)so.onclick=function(){if(confirm('Sign out of this account?'))Android.googleSignOut()};if(cv)cv.onclick=function(){text('verifyMsg','Checking verification…');Android.checkEmailVerified()};if(rv)rv.onclick=function(){text('verifyMsg','Sending verification email…');Android.resendVerification()};if(vs)vs.onclick=function(){Android.googleSignOut();showVerify(false)};for(i=0;i<sw.length;i++)sw[i].onclick=function(){setMode(this.getAttribute('data-switch-auth'))};for(i=0;i<eyes.length;i++)eyes[i].onclick=function(){togglePassword(this)};var ab=E('authBackBtn');if(ab)ab.onclick=function(){if(currentMode==='signup')setMode('login')};setMode('login');if(window.Android&&Android.authState)Android.authState()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
