from pathlib import Path
import re, sys
assets=Path(sys.argv[1] if len(sys.argv)>1 else 'app/src/main/assets')
app=assets/'app.js'; s=app.read_text()
old="function overtimeMinutes(a,b){var s=setGet();return Math.max(0,workMinutes(a,b)-(s.h*60+s.m+s.otDelay))}"
new="""function overtimeMinutes(a,b){var s=setGet();return Math.max(0,workMinutes(a,b)-(s.h*60+s.m+s.otDelay))}\nfunction requiredMinutesForStatus(st){var s=setGet(),std=s.h*60+s.m;if(st==='Paid Leave'||st==='Holiday'||st==='Week Off')return 0;if(st==='Half Day')return Math.round(std/2);return std}\nfunction dailyBalanceMinutes(x){var s=setGet(),req=requiredMinutesForStatus(x.status),worked=workMinutes(x.checkIn,x.checkOut),diff;if(x.status==='Paid Leave'||x.status==='Holiday'||x.status==='Week Off')return 0;if(x.status==='Absent'||x.status==='Unpaid Leave')return-req;diff=worked-req;return diff>0?Math.max(0,diff-s.otDelay):diff}\nfunction monthBalanceMinutes(month){var a=dataGet(),n=0,i;for(i=0;i<a.length;i++)if(a[i].date.indexOf(month)===0)n+=dailyBalanceMinutes(a[i]);return n}\nfunction signedDuration(min){min=Math.round(min||0);var sign=min<0?'-':min>0?'+':'';min=Math.abs(min);return sign+Math.floor(min/60)+'h '+P(min%60)+'m'}"""
if old not in s: raise SystemExit('overtime helper not found')
s=s.replace(old,new)
s=re.sub(r"function salaryCalc\(month\)\{.*?\n\}","""function salaryCalc(month){\n var sal=salaryGet(),s=setGet(),a=dataGet(),dparts=month.split('-'),days=new Date(+dparts[0],+dparts[1],0).getDate(),std=s.h*60+s.m||1,dayRate=sal.monthly/days,hourRate=dayRate/(std/60),regularMin=0,net=0,i,x,w,req;\n for(i=0;i<a.length;i++){x=a[i];if(x.date.indexOf(month)!==0)continue;w=workMinutes(x.checkIn,x.checkOut);req=requiredMinutesForStatus(x.status);net+=dailyBalanceMinutes(x);if(x.status==='Paid Leave'||x.status==='Holiday'||x.status==='Week Off')regularMin+=std;else if(x.status==='Present')regularMin+=Math.min(std,w);else if(x.status==='Half Day')regularMin+=Math.min(Math.round(std/2),w)}\n var paid=regularMin/std,otPay=(Math.max(0,net)/60)*hourRate*sal.otMultiplier,earned=(regularMin/60)*hourRate+otPay;\n return{days:days,paid:paid,ot:Math.max(0,net),net:net,shortfall:Math.max(0,-net),dayRate:dayRate,hourRate:hourRate,otPay:otPay,earned:earned}\n}""",s,count=1,flags=re.S)
s=re.sub(r"function renderHome\(\)\{.*?\n\}","""function renderHome(){\n var x=currentRecord(),a=dataGet(),mo=monthNow(),p=0,l=0,i,sc=salaryCalc(mo);\n E('homeIn').textContent=x?timeText(x.checkIn):'--:--';E('homeOut').textContent=x?timeText(x.checkOut):'--:--';E('homeWorked').textContent=x?durationText(workMinutes(x.checkIn,x.checkOut)):'--';\n for(i=0;i<a.length;i++)if(a[i].date.indexOf(mo)===0){if(a[i].status==='Present')p++;if(a[i].status==='Paid Leave'||a[i].status==='Unpaid Leave')l++}\n E('qPresent').textContent=p;E('qLeave').textContent=l;E('qOT').textContent=signedDuration(sc.net);E('qSalary').textContent=money(sc.earned);renderPunchButton()\n}""",s,count=1,flags=re.S)
s=s.replace("'<div class=\"recordMeta\">OT: '+durationText(overtimeMinutes(x.checkIn,x.checkOut))", "'<div class=\"recordMeta\">Balance: '+signedDuration(dailyBalanceMinutes(x))")
s=re.sub(r"function exportCSV\(\)\{.*?\nfunction importCSV\(ev\)\{.*?\n\}",lambda m:"""function csvCell(v){v=String(v==null?'':v);return /[\",\\n\\r]/.test(v)?'\"'+v.replace(/\"/g,'\"\"')+'\"':v}\nfunction parseCSV(txt){var rows=[],row=[],cell='',q=false,i,ch;for(i=0;i<txt.length;i++){ch=txt.charAt(i);if(q){if(ch==='\"'&&txt.charAt(i+1)==='\"'){cell+='\"';i++}else if(ch==='\"')q=false;else cell+=ch}else if(ch==='\"')q=true;else if(ch===','){row.push(cell);cell=''}else if(ch==='\\n'){row.push(cell);rows.push(row);row=[];cell=''}else if(ch!=='\\r')cell+=ch}row.push(cell);if(row.length>1||row[0])rows.push(row);return rows}\nfunction exportCSV(){var a=dataGet(),s=setGet(),lines=[['Date','Status','Check In','Check Out','Working Minutes','Standard Hours','Standard Minutes','OT Delay Minutes','Daily Balance Minutes','Reason','Notes']],i,row,txt,name;for(i=0;i<a.length;i++){row=[a[i].date,a[i].status,a[i].checkIn||'',a[i].checkOut||'',workMinutes(a[i].checkIn,a[i].checkOut),s.h,s.m,s.otDelay,dailyBalanceMinutes(a[i]),a[i].reason||'',a[i].notes||''];lines.push(row)}txt=lines.map(function(r){return r.map(csvCell).join(',')}).join('\\n');name='attendance_'+nowDate()+'.csv';try{if(window.Android&&Android.saveCsv){Android.saveCsv(name,txt);toast('CSV saved');return}}catch(e){}var blob=new Blob([txt],{type:'text/csv'}),url=URL.createObjectURL(blob),aTag=document.createElement('a');aTag.href=url;aTag.download=name;aTag.click();URL.revokeObjectURL(url)}\nfunction importCSV(ev){var f=ev.target.files[0];if(!f)return;var r=new FileReader();r.onload=function(){var rows=parseCSV(String(r.result||'')),a=dataGet(),head=rows[0]||[],map={},i,j,c,e,b,count=0,skip=0;for(i=0;i<head.length;i++)map[String(head[i]).trim().toLowerCase()]=i;function col(names,def){var n,idx;for(n=0;n<names.length;n++){idx=map[names[n]];if(typeof idx==='number')return c[idx]||def}return def}for(i=1;i<rows.length;i++){c=rows[i];if(!c||!c.length)continue;var date=col(['date'],'');if(!/^\\d{4}-\\d{2}-\\d{2}$/.test(date)){skip++;continue}e={id:idNew(),date:date,status:col(['status'],'Present'),checkIn:col(['check in','checkin'],'') ,checkOut:col(['check out','checkout'],'') ,reason:col(['reason','remarks'],'') ,notes:col(['notes'],'')};b=[];for(j=0;j<a.length;j++)if(a[j].date!==e.date)b.push(a[j]);b.push(e);a=b;count++}dataPut(a);toast('Imported '+count+' records'+(skip?' • '+skip+' skipped':''));renderAll();ev.target.value=''};r.readAsText(f)}""",s,count=1,flags=re.S)
s=s.replace("E('removePhoto').onclick=", "if(E('removePhoto'))E('removePhoto').onclick=")
app.write_text(s)
html=(assets/'index.html').read_text()
html=re.sub(r'\s*<button class="profileCardDelete" id="removePhoto".*?</button>','',html,count=1,flags=re.S)
html=html.replace('<button class="btn primary fullBtn" id="saveProfile" type="button">Save Profile</button>','<button class="btn primary fullBtn" id="saveProfile" type="button">Save Profile</button><button class="btn dangerOutline fullBtn" id="deleteProfileBtn" type="button">Delete Profile</button>')
html=html.replace('<div class="label">Theme</div><div class="seg"><button id="themeLight" type="button">Light</button><button id="themeDark" type="button">Dark</button></div>','<div class="label">Theme</div><div class="themeVisualToggle"><button id="themeLight" type="button" aria-label="Light mode"><span>☀</span><small>Light</small></button><button id="themeDark" type="button" aria-label="Dark mode"><span>☾</span><small>Dark</small></button></div>')
html=html.replace('<button class="btn ghost" id="exportBtn" type="button">Export CSV</button>','<button class="btn ghost" id="exportBtn" type="button">Export CSV</button><button class="btn ghost" id="exportExcelBtn" type="button">Export Excel</button>')
html=html.replace('<button class="punchBtn" id="punchBtn" type="button">','<button class="punchBtn" id="punchBtn" type="button"><svg class="workProgressRing" id="workProgressRing" viewBox="0 0 120 120" aria-hidden="true"><circle class="workProgressTrack" cx="60" cy="60" r="56"></circle><circle class="workProgressValue" id="workProgressValue" cx="60" cy="60" r="56"></circle></svg><span class="workProgressText" id="workProgressText"></span>')
html=html.replace('<small>Overtime</small></div>','<small>Net OT / Deficit</small></div>',1)
needle='<script src="cloud-ui.js"></script>'
html=html.replace(needle, needle+'\n<script src="xlsx.full.min.js"></script>\n<script src="v11-ui.js"></script>')
html=html.replace('<link rel="stylesheet" href="cloud-ui.css">','<link rel="stylesheet" href="cloud-ui.css">\n<link rel="stylesheet" href="v11-ui.css">')
(assets/'index.html').write_text(html)
