(function(){
'use strict';
function E(id){return document.getElementById(id)}
function P(n){n=parseInt(n,10)||0;return n<10?'0'+n:String(n)}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
var lastAction=null,confirmBypass=false;
document.addEventListener('click',function(e){var t=e.target.closest?e.target.closest('button,label'):null;if(t)lastAction=t},true);
function dialog(title,msg,buttons,done,input){var old=E('appDialogOverlay');if(old)old.parentNode.removeChild(old);var o=document.createElement('div');o.id='appDialogOverlay';o.className='appDialogOverlay show';var b='',i;for(i=0;i<buttons.length;i++)b+='<button type="button" class="appDialogBtn '+(buttons[i].kind||'')+'" data-i="'+i+'">'+esc(buttons[i].label)+'</button>';o.innerHTML='<div class="appDialogCard"><div class="appDialogTitle">'+esc(title)+'</div><div class="appDialogText">'+esc(msg)+'</div>'+(input?'<input class="appDialogInput" id="appDialogInput" placeholder="'+esc(input.placeholder||'')+'" '+(input.type?'type="'+input.type+'"':'')+'>':'')+'<div class="appDialogActions">'+b+'</div></div>';document.body.appendChild(o);o.onclick=function(e){var x=e.target.closest&&e.target.closest('.appDialogBtn');if(!x)return;var idx=parseInt(x.getAttribute('data-i'),10),val=E('appDialogInput')?E('appDialogInput').value:'';document.body.removeChild(o);if(done)done(idx,val)};return o}
window.appDialog=dialog;
window.alert=function(msg){dialog('Notice',String(msg||''),[{label:'OK',kind:'primary'}])};
window.confirm=function(msg){if(confirmBypass){confirmBypass=false;return true}var action=lastAction;dialog('Please confirm',String(msg||''),[{label:'Confirm',kind:'primary'},{label:'Cancel',kind:'outline'}],function(i){if(i===0&&action){confirmBypass=true;action.click()}});return false};
function getSettings(){var s={h:9,m:0,otDelay:30};try{var o=JSON.parse(localStorage.getItem('attendance_settings_v8')||'{}')||{};if(typeof o.h!=='undefined')s.h=+o.h||0;if(typeof o.m!=='undefined')s.m=+o.m||0;if(typeof o.otDelay!=='undefined')s.otDelay=+o.otDelay||0}catch(e){}return s}
function today(){var d=new Date();return d.getFullYear()+'-'+P(d.getMonth()+1)+'-'+P(d.getDate())}
function getRecords(){try{return JSON.parse(localStorage.getItem('attendance_v8')||'[]')||[]}catch(e){return[]}}
function currentRecord(){var a=getRecords(),d=today(),i;for(i=0;i<a.length;i++)if(a[i].date===d)return a[i];return null}
function minFrom(t){if(!t)return 0;var a=t.split(':');return (+a[0])*60+(+a[1])}
function updateRing(){var ring=E('workProgressValue'),txt=E('workProgressText'),x=currentRecord(),s=getSettings(),std=s.h*60+s.m;if(!ring||!txt)return;var C=351.86;ring.style.strokeDasharray=C;ring.style.strokeDashoffset=C;if(!x||!x.checkIn||x.checkOut||!std){txt.textContent='';return}var now=new Date(),start=minFrom(x.checkIn),cur=now.getHours()*60+now.getMinutes(),elapsed=cur-start;if(elapsed<0)elapsed+=1440;var pct=Math.max(0,Math.min(1,elapsed/std)),left=Math.max(0,std-elapsed);ring.style.strokeDashoffset=String(C*(1-pct));txt.textContent=left>0?(P(Math.floor(left/60))+':'+P(left%60)+' left'):'Work time done'}
setInterval(updateRing,1000);setTimeout(updateRing,200);
function decorateSelect(sel){if(!sel||sel.getAttribute('data-customized'))return;sel.setAttribute('data-customized','1');sel.classList.add('customNativeSelect');var w=document.createElement('div');w.className='customSelect';var b=document.createElement('button');b.type='button';b.className='customSelectButton';var m=document.createElement('div');m.className='customSelectMenu';w.appendChild(b);w.appendChild(m);sel.parentNode.insertBefore(w,sel.nextSibling);function rebuild(){var i,o,html='';for(i=0;i<sel.options.length;i++){o=sel.options[i];html+='<button type="button" data-v="'+esc(o.value)+'" class="customSelectOption'+(o.value===sel.value?' selected':'')+'">'+esc(o.text)+'</button>'}m.innerHTML=html;b.textContent=sel.options[sel.selectedIndex]?sel.options[sel.selectedIndex].text:'Select'}function close(){w.classList.remove('open')}b.onclick=function(e){e.stopPropagation();var all=document.querySelectorAll('.customSelect.open'),j;for(j=0;j<all.length;j++)if(all[j]!==w)all[j].classList.remove('open');rebuild();w.classList.toggle('open')};m.onclick=function(e){var x=e.target.closest('.customSelectOption');if(!x)return;sel.value=x.getAttribute('data-v');sel.dispatchEvent(new Event('change',{bubbles:true}));rebuild();close()};sel.addEventListener('change',rebuild);rebuild()}
function decorateAllSelects(root){var a=(root||document).querySelectorAll('select'),i;for(i=0;i<a.length;i++)decorateSelect(a[i])}
document.addEventListener('click',function(){var a=document.querySelectorAll('.customSelect.open'),i;for(i=0;i<a.length;i++)a[i].classList.remove('open')});
var calInput=null,calDate=new Date();
function ensureCalendar(){if(E('customCalendarOverlay'))return;var o=document.createElement('div');o.id='customCalendarOverlay';o.className='customCalendarOverlay';o.innerHTML='<div class="customCalendarCard"><div class="calendarHead"><button type="button" id="calPrev">‹</button><b id="calTitle"></b><button type="button" id="calNext">›</button></div><div class="calendarWeek"><span>Mo</span><span>Tu</span><span>We</span><span>Th</span><span>Fr</span><span>Sa</span><span>Su</span></div><div class="calendarGrid" id="calendarGrid"></div><button type="button" class="appDialogBtn primary calendarDone" id="calDone">Done</button></div>';document.body.appendChild(o);E('calPrev').onclick=function(){calDate.setMonth(calDate.getMonth()-1);renderCal()};E('calNext').onclick=function(){calDate.setMonth(calDate.getMonth()+1);renderCal()};E('calDone').onclick=function(){if(calInput){calInput.value=calDate.getFullYear()+'-'+P(calDate.getMonth()+1)+'-'+P(calDate.getDate());calInput.dispatchEvent(new Event('change',{bubbles:true}));var btn=calInput._calBtn;if(btn)btn.textContent=calInput.value||'Select date'}o.classList.remove('show')};o.onclick=function(e){if(e.target===o)o.classList.remove('show')}}
function renderCal(){ensureCalendar();E('calTitle').textContent=calDate.toLocaleDateString(undefined,{month:'long',year:'numeric'});var y=calDate.getFullYear(),m=calDate.getMonth(),first=new Date(y,m,1),start=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate(),prev=new Date(y,m,0).getDate(),html='',i,n,cls;for(i=0;i<42;i++){if(i<start){n=prev-start+i+1;cls='muted'}else if(i>=start+days){n=i-start-days+1;cls='muted'}else{n=i-start+1;cls=(n===calDate.getDate()?'selected ':'')+(y===new Date().getFullYear()&&m===new Date().getMonth()&&n===new Date().getDate()?'today':'')}html+='<button type="button" class="'+cls+'" data-day="'+(i>=start&&i<start+days?n:'')+'">'+n+'</button>'}E('calendarGrid').innerHTML=html;E('calendarGrid').onclick=function(e){var b=e.target.closest('button'),day=b&&b.getAttribute('data-day');if(!day)return;calDate.setDate(+day);renderCal()}}
function decorateDate(inp){if(!inp||inp.getAttribute('data-customized'))return;inp.setAttribute('data-customized','1');inp.classList.add('customNativeDate');var b=document.createElement('button');b.type='button';b.className='customDateButton';b.textContent=inp.value||'Select date';inp.parentNode.insertBefore(b,inp.nextSibling);inp._calBtn=b;b.onclick=function(){calInput=inp;var p=inp.value?inp.value.split('-'):null;calDate=p?new Date(+p[0],+p[1]-1,+p[2]):new Date();renderCal();E('customCalendarOverlay').classList.add('show')};inp.addEventListener('change',function(){b.textContent=inp.value||'Select date'})}
function decorateDates(root){var a=(root||document).querySelectorAll('input[type="date"]'),i;for(i=0;i<a.length;i++)decorateDate(a[i])}
function exportExcel(){if(!window.XLSX){dialog('Excel export','Excel engine is not available.',[{label:'OK',kind:'primary'}]);return}var a=getRecords(),s=getSettings(),sal={monthly:0,otMultiplier:1};try{sal=JSON.parse(localStorage.getItem('attendance_salary_v9')||'{}')||sal}catch(e){}var months={},i,x,mo;for(i=0;i<a.length;i++){x=a[i];mo=x.date.slice(0,7);if(!months[mo])months[mo]=[];months[mo].push(x)}var wb=XLSX.utils.book_new(),keys=Object.keys(months).sort(),std=s.h*60+s.m;function work(x){if(!x.checkIn||!x.checkOut)return 0;var aa=minFrom(x.checkIn),bb=minFrom(x.checkOut);if(bb<aa)bb+=1440;return bb-aa}function req(x){if(x.status==='Paid Leave'||x.status==='Holiday'||x.status==='Week Off')return 0;if(x.status==='Half Day')return Math.round(std/2);return std}function bal(x){var r=req(x),w=work(x),d;if(x.status==='Paid Leave'||x.status==='Holiday'||x.status==='Week Off')return 0;if(x.status==='Absent'||x.status==='Unpaid Leave')return-r;d=w-r;return d>0?Math.max(0,d-s.otDelay):d}function hm(n){var sg=n<0?'-':'';n=Math.abs(Math.round(n||0));return sg+Math.floor(n/60)+':'+P(n%60)}for(i=0;i<keys.length;i++){mo=keys[i];var rows=[['Date','Day','In Time','Out Time','Work Hours','Required Hours','Extra Hours','Short Hours','Net Balance','Status','Remarks']],arr=months[mo].sort(function(q,w){return q.date.localeCompare(w.date)}),tw=0,tr=0,te=0,ts=0,nb=0,j,b,r,wk;for(j=0;j<arr.length;j++){x=arr[j];wk=work(x);r=req(x);b=bal(x);tw+=wk;tr+=r;if(b>0)te+=b;else ts+=-b;nb+=b;rows.push([x.date,new Date(x.date+'T00:00:00').toLocaleDateString(undefined,{weekday:'long'}),x.checkIn||'',x.checkOut||'',hm(wk),hm(r),hm(Math.max(0,b)),hm(Math.max(0,-b)),hm(b),x.status,(x.reason||'')+(x.notes?((x.reason?' • ':'')+x.notes):'')])}rows.push([]);rows.push(['TOTAL','','','',hm(tw),hm(tr),hm(te),hm(ts),hm(nb),'','']);var ws=XLSX.utils.aoa_to_sheet(rows);ws['!cols']=[{wch:13},{wch:12},{wch:10},{wch:10},{wch:12},{wch:14},{wch:12},{wch:12},{wch:12},{wch:14},{wch:28}];XLSX.utils.book_append_sheet(wb,ws,new Date(+mo.slice(0,4),+mo.slice(5)-1,1).toLocaleDateString('en',{month:'short',year:'2-digit'}).replace(' ',''))}var sum=[['Month','Net OT / Deficit','Monthly Salary']],k;for(i=0;i<keys.length;i++){mo=keys[i];var n=0;for(k=0;k<months[mo].length;k++)n+=bal(months[mo][k]);sum.push([mo,hm(n),sal.monthly||0])}XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(sum),'Salary Summary');var base64=XLSX.write(wb,{bookType:'xlsx',type:'base64'}),name='My_Attendance_'+today()+'.xlsx';try{if(window.Android&&Android.saveBase64File){Android.saveBase64File(name,'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',base64);dialog('Excel exported','Workbook saved to Downloads / My Attendance / Documents.',[{label:'OK',kind:'primary'}]);return}}catch(e){}dialog('Excel export','Export is available in the Android app.',[{label:'OK',kind:'primary'}])}
function clearLocalEverything(){var keys=[],i;for(i=0;i<localStorage.length;i++)keys.push(localStorage.key(i));for(i=0;i<keys.length;i++)if(keys[i]&&keys[i].indexOf('attendance_')===0)localStorage.removeItem(keys[i]);try{indexedDB.deleteDatabase('attendance_docs_v81')}catch(e){}}
function deleteProfileFlow(){dialog('Delete profile?','This permanently removes attendance, salary, settings, documents, cloud backup and your account. This cannot be undone.',[{label:'Continue',kind:'danger'},{label:'Cancel',kind:'outline'}],function(i){if(i!==0)return;var email=E('cloudEmail')?E('cloudEmail').textContent:'';dialog('Verify account','Type your registered email address to continue.',[{label:'Verify',kind:'danger'},{label:'Cancel',kind:'outline'}],function(j,val){if(j!==0)return;if(String(val||'').trim().toLowerCase()!==String(email||'').trim().toLowerCase()){dialog('Verification failed','The email address did not match the signed-in account.',[{label:'OK',kind:'primary'}]);return}dialog('Final confirmation','Type DELETE to permanently erase this profile.',[{label:'Delete permanently',kind:'danger'},{label:'Cancel',kind:'outline'}],function(k,word){if(k!==0)return;if(String(word||'').trim()!=='DELETE'){dialog('Not deleted','You must type DELETE exactly.',[{label:'OK',kind:'primary'}]);return}if(window.Android&&Android.deleteAccountData){Android.deleteAccountData()}else{clearLocalEverything();if(window.Android&&Android.googleSignOut)Android.googleSignOut();location.reload()}},{placeholder:'DELETE'})},{placeholder:'Email address',type:'email'})})}
window.onProfileDeleteResult=function(ok,msg){if(ok){clearLocalEverything();dialog('Profile deleted','Your local profile data and account were deleted.',[{label:'OK',kind:'primary'}],function(){location.reload()})}else dialog('Could not delete profile',msg||'Please sign out, sign in again and retry.',[{label:'OK',kind:'primary'}])};
function init(){decorateAllSelects(document);decorateDates(document);var ex=E('exportExcelBtn'),del=E('deleteProfileBtn');if(ex)ex.onclick=exportExcel;if(del)del.onclick=deleteProfileFlow;var mo=new MutationObserver(function(ms){var i,j;for(i=0;i<ms.length;i++)for(j=0;j<ms[i].addedNodes.length;j++){var n=ms[i].addedNodes[j];if(n.nodeType===1){decorateAllSelects(n);decorateDates(n)}}});mo.observe(document.body,{childList:true,subtree:true});updateRing()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();